const { Event } = require('../models');

const eventdata = [
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 1,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 2,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 3,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 4,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 5,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 6,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 7,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 8,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 9,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Overwatch 2 League",
    "event_description": "Seeking a place to share your thoughts & creations? Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Collisto Protocol",
    "event_description": "Creative Thoughts is all about collaborating, sharing, conversation, and more! We have a wide variety of topics however we’re always listening to suggestions from the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Pokemon Trainers",
    "event_description": "Are you an adult (21+) who is interested in video games and wanting to make new friends to game with? Do you want to participate in nerdy activities and play classic and contemporary games?",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Elden Ring Wizards",
    "event_description": "Greetings! We're a group of people that believe Elden Ring its applications have a positive impact on our world's future.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "All Things Mario",
    "event_description": "Whatever game you’re interested in getting better at this year, Shell Geist can help. Join the community today and help others by leaving advice or learn from others and ask questions.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Warzone Meetup",
    "event_description": "Welcome to the official r/Warzone Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "FIFA Mecca",
    "event_description": "Welcome to the official r/Fifa Discord server! Please take a few moments to read through our rules before joining the community.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Star Wars",
    "event_description": "Welcome to the official Star Wars Server community! Please help us keep this server a welcome and friendly place by respecting our rules.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Cyberpunk 2077",
    "event_description": "Welcome to the Official Cyberpunk Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
  {
    "group_id": 10,
    "profile_id": 8,
    "event_name": "Assassin's Creed Stealth",
    "event_description": "Welcome to the Official Assassin's Creed Game server! Hope you’ll enjoy your time here and engage in interesting conversations.",
    "media_location_url": "https://i.imgur.com/v3viNdd.jpg",
  },
]

const seedEvents = () => Event.bulkCreate(eventdata);

module.exports = seedEvents;